# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nextappforlocal

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://nextappforlocal.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_dacafab545e445ce8c9157365500b4be }}
        password: ${{ secrets.AzureAppService_ContainerPassword_98bfa04e7a11444b9fc55010f76f1166 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: nextappforlocal.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_dacafab545e445ce8c9157365500b4be }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nextappforlocal'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4fb28e5caae04fbf86b5a1302b61d4c1 }}
        images: 'nextappforlocal.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_dacafab545e445ce8c9157365500b4be }}/appsvc/staticsite:${{ github.sha }}'